CREATE TABLE Plan (
plan_id DECIMAL(10) NOT NULL,
plan_name VARCHAR(255) NOT NULL,
price DECIMAL(12,2) NOT NULL,
description VARCHAR(255),
PRIMARY KEY (PLAN_ID));



CREATE TABLE Customers (
cust_id DECIMAL(10) NOT NULL,
cust_fname VARCHAR(40) NOT NULL,
cust_lname VARCHAR(40) NOT NULL,
plan_id DECIMAL(10) NOT NULL,
password VARCHAR(40) NOT NULL,
email VARCHAR(255) NOT NULL,
phone DECIMAL(20),
address VARCHAR(255),
card_num DECIMAL(20) NOT NULL,
card_cvv DECIMAL(10) NOT NULL,
PRIMARY KEY (CUST_ID),
FOREIGN KEY (PLAN_ID) REFERENCES plan);

ALTER TABLE Customers
MODIFY (plan_id DECIMAL(10) NULL);



CREATE TABLE Movie (
movie_id DECIMAL(10) NOT NULL,
movie_name VARCHAR(255) NOT NULL,
release_date DATE,
description VARCHAR(255),
PRIMARY KEY (MOVIE_ID));






CREATE TABLE Queue (
queue_id DECIMAL(10) NOT NULL,
cust_id DECIMAL(10) NOT NULL,
movie_id DECIMAL(10) NOT NULL,
add_date DATE,
PRIMARY KEY (QUEUE_ID),
FOREIGN KEY (CUST_ID) REFERENCES customers,
FOREIGN KEY (MOVIE_ID) REFERENCES movie);




CREATE TABLE Directors (
direct_id DECIMAL(10) NOT NULL,
direct_fname VARCHAR(255) NOT NULL,
direct_lname VARCHAR(255) NOT NULL,
PRIMARY KEY (DIRECT_ID));


CREATE TABLE Direct_Movie (
direct_id DECIMAL(10) NOT NULL,
movie_id DECIMAL(10) NOT NULL,
PRIMARY KEY (DIRECT_ID, MOVIE_ID),
FOREIGN KEY (DIRECT_ID) REFERENCES directors,
FOREIGN KEY (MOVIE_ID) REFERENCES movie);




CREATE TABLE Delivery_Services (
deliver_id DECIMAL(10) NOT NULL,
deliver_name VARCHAR(255) NOT NULL,
PRIMARY KEY (DELIVER_ID));




CREATE TABLE Department (
depart_id DECIMAL(10) NOT NULL,
depart_name VARCHAR(255) NOT NULL,
PRIMARY KEY (DEPART_ID));




CREATE TABLE Employee (
emp_id DECIMAL(10) NOT NULL,
emp_fname VARCHAR(255) NOT NULL,
emp_lname VARCHAR(255) NOT NULL,
depart_id DECIMAL(10) NOT NULL,
email VARCHAR(255),
phone DECIMAL(20),
PRIMARY KEY (EMP_ID),
FOREIGN KEY (DEPART_ID) REFERENCES department);



CREATE TABLE Rental_Transactions (
rent_id DECIMAL(10) NOT NULL,
cust_id DECIMAL(10) NOT NULL,
deliver_id DECIMAL(12,2),
rent_date DATE,
tracking_num DECIMAL(25),
emp_id DECIMAL(10),
PRIMARY KEY (RENT_ID),
FOREIGN KEY (CUST_ID) REFERENCES customers,
FOREIGN KEY (DELIVER_ID) REFERENCES delivery_services,
FOREIGN KEY (EMP_ID) REFERENCES employee);




CREATE TABLE DVD_Distributor (
dist_id DECIMAL(10) NOT NULL,
dist_name VARCHAR(255) NOT NULL,
email VARCHAR(255),
phone DECIMAL(10),
PRIMARY KEY (DIST_ID));




CREATE TABLE DVD (
DVD_id DECIMAL(10) NOT NULL,
movie_id DECIMAL(10) NOT NULL,
quantity DECIMAL(10),
dist_id DECIMAL(10),
PRIMARY KEY (DVD_ID),
FOREIGN KEY (MOVIE_ID) REFERENCES movie,
FOREIGN KEY (DIST_ID) REFERENCES dvd_distributor);





CREATE TABLE DVD_Rent (
DVD_id DECIMAL(10) NOT NULL,
rent_id DECIMAL(10) NOT NULL,
PRIMARY KEY (DVD_ID, RENT_ID),
FOREIGN KEY (DVD_ID) REFERENCES DVD,
FOREIGN KEY (RENT_ID) REFERENCES rental_transactions);


CREATE TABLE Return_Transactions (
return_id DECIMAL(10) NOT NULL,
cust_id DECIMAL(10) NOT NULL,
return_date DATE,
deliver_id DECIMAL(10) NOT NULL,
tracking_num VARCHAR(40),
emp_id DECIMAL(10) NOT NULL,
PRIMARY KEY (RETURN_ID),
FOREIGN KEY (CUST_ID) REFERENCES customers,
FOREIGN KEY (DELIVER_ID) REFERENCES delivery_services,
FOREIGN KEY (EMP_ID) REFERENCES employee);




CREATE TABLE DVD_Return (
DVD_id DECIMAL(10) NOT NULL,
return_id DECIMAL(10) NOT NULL,
PRIMARY KEY (DVD_ID, RETURN_ID),
FOREIGN KEY (DVD_ID) REFERENCES DVD,
FOREIGN KEY (RETURN_ID) REFERENCES return_transactions);


CREATE TABLE Actors (
actor_id DECIMAL(10) NOT NULL,
actor_fname VARCHAR(255) NOT NULL,
actor_lname VARCHAR(255) NOT NULL,
PRIMARY KEY (ACTOR_ID));



CREATE TABLE Act_Movie (
actor_id DECIMAL(10) NOT NULL,
movie_id DECIMAL(10) NOT NULL,
PRIMARY KEY (ACTOR_ID, MOVIE_ID),
FOREIGN KEY (ACTOR_ID) REFERENCES actors,
FOREIGN KEY (MOVIE_ID) REFERENCES movie);




CREATE TABLE Producers (
pro_id DECIMAL(10) NOT NULL,
pro_fname VARCHAR(255) NOT NULL,
pro_lname VARCHAR(255) NOT NULL,
PRIMARY KEY (PRO_ID));



CREATE TABLE Produce_Movie (
pro_id DECIMAL(10) NOT NULL,
movie_id DECIMAL(10) NOT NULL,
PRIMARY KEY (PRO_ID, MOVIE_ID),
FOREIGN KEY (PRO_ID) REFERENCES producers,
FOREIGN KEY (MOVIE_ID) REFERENCES movie);


COMMIT;